# Generated by Django 3.2.6 on 2021-09-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0002_auto_20210905_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1630848310.0023525),
        ),
    ]
